### ISSUE TITLE
suggestions

### ISSUE THREAD

**Issue by Jacksparrow120** [localghosts/store-it-frontend#28]
1) Password should be alpha-numeric  and it would be great if you make it compulsory to add any special character in password.
2) OTP section needed to be encrypted.
3) Cart's section needs an improvement as some of the item name is overlapping with other things (please refer attachment for exact issue).
4) It would be better if product category drop down list is in the alphabetical order in seller section.
![WhatsApp Image 2022-04-16 at 11 43 06 PM](https://user-images.githubusercontent.com/79086106/163686696-3e0549e5-c250-44e3-bbd1-46f1c8052268.jpeg)

**Comment by bhuvansingla** [comment]
Can you please elaborate on

> OTP section needed to be encrypted

**Comment by 1-Harshit** [comment]
- Closed with #30
