### ISSUE TITLE
[Error] Can't open application

### ISSUE THREAD

**Issue by Jacksparrow120** [localghosts/store-it-frontend#29]
At first I can't able to open this application it was showing some application error.
Please look into this matter.

**Comment by 1-Harshit** [comment]
@Jacksparrow120 Maybe the documentation can sort this confusion
relevant info could be found [here](https://github.com/localghosts/store-it/blob/main/README.md#deployment) read the *NOTE*

Quoting text for ease:
> ## About deployement
> The web app is deployed at: [store-it-frontend.herokuapp.com](https://store-it-frontend.herokuapp.com/)
> 
> Note: This is hosted on Heroku which hibernates upon inactivity on website. It may take upto a minute to load for the first time post inactivity.

Feel free to reopen the issue if this is not a satisfactory or relevant reply.

Thanks
Team localghosts
